services:
  - type: web
    name: whispers-of-us-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: APP_NAME
        value: whispers-backend
      - key: APP_ENVIRONMENT
        value: production
      - key: LOGGING_LEVEL_ROOT
        value: INFO
      - key: LOGGING_LEVEL_APP
        value: INFO
      - key: FILE_UPLOAD_MAX_SIZE
        value: 10MB
      - key: FILE_UPLOAD_MAX_REQUEST_SIZE
        value: 10MB
      # These will be set as secrets in Render dashboard
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_KEY_PATH
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false 